name: Publish and Deploy to Cloud Run

on:
  push:
    tags:
      - 'v*'  # Trigger only on tags that start with "v" (e.g., v1.0.0)

jobs:
  publish:
    name: Publish Docker Image to GHCR
    runs-on: ubuntu-latest
    env:
      # Use built-in GitHub variables for the image tag.
      GHCR_IMAGE: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.ref_name }}
    outputs:
      image: ${{ steps.load_and_tag.outputs.new_image }}
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Build Docker Image with Nix Flake
        run: |
          nix build "github:${{ github.repository_owner }}/${{ github.event.repository.name }}/${{ github.ref_name }}#docker"

      - name: Load and Retag Docker Image
        id: load_and_tag
        run: |
          # Load the Docker image from the file.
          output=$(docker load < result)
          echo "$output"
          # Extract the image name from the output.
          # Expected output: "Loaded image: image_name:tag"
          image=$(echo "$output" | awk -F': ' '/Loaded image/ {print $2}')
          echo "Loaded image: $image"
          # Retag the image using the built-in GHCR_IMAGE variable.
          docker tag "$image" "$GHCR_IMAGE"
          echo "New image tag: $GHCR_IMAGE"
          # Set the output variable for the deploy job.
          echo "new_image=$GHCR_IMAGE" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker Image to GHCR
        run: docker push $GHCR_IMAGE

  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@71f986410dfbc7added4569d411d040a91dc6935  # v2.1.8
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@9c5864eab7354d2e132307e685a2272655932799  #v2.7.3
        with:
          service: msxrom2vhd-web
          image: ${{ needs.publish.outputs.image }}
